export type ProfessionalRouteSlug =
  | "maker"
  | "consultor-funcional"
  | "developer"
  | "solution-architect"
  | "dynamics-365-customer-engagement"
  | "dynamics-365-customer-insights"
  | "dynamics-365-field-service"
  | "finance-operations"
  | "ai-copilot"
  | "rpa"
  | "fundamentos-power-platform"
  | "dynamics-365-sales"
  | "dynamics-365-customer-service"
  | "dynamics-365-customer-insights-data"
  | "dynamics-365-customer-insights-journeys"
  | "empleabilidad";

export interface ProfessionalRoute {
  slug: ProfessionalRouteSlug;
  title: string;
  role: string;
  summary: string;
  outcome: string;
  level: "Inicial" | "Intermedio" | "Avanzado" | "Especialización";
  accent: string;
  modules: number[];
  labs: string[];
  competencies: string[];
  status:
    | "Disponible"
    | "Parcial"
    | "Especialización en construcción"
    | "Avanzado — especializaciones en expansión"
    | "Awareness avanzado — práctica en roadmap"
    | "Archivada / futura especialización";
  gapNote?: string;
  nextRouteSlug?: ProfessionalRouteSlug;
  /** Slug del lab que funciona como proyecto final evaluable de la ruta. */
  capstoneLabSlug?: string;
  /** moduleId del módulo que funciona como proyecto final cuando el capstone no es un lab (p. ej. el módulo 41 de arquitectura). */
  capstoneModuleId?: number;
  /** Entregables concretos del capstone que deberían reunirse como evidencia de portafolio. */
  portfolioEvidence: string[];
}

const PROFESSIONAL_ROUTES: ProfessionalRoute[] = [
  {
    slug: "maker",
    title: "Ruta Maker",
    role: "Usuario de negocio que construye soluciones low-code",
    summary: "Aprende a modelar datos simples, crear apps, automatizar procesos y validar soluciones internas sin entrar todavía en desarrollo avanzado.",
    outcome: "Construir una solución departamental con Canvas App, Model-Driven App, Dataverse básico y Power Automate.",
    level: "Inicial",
    accent: "#107C10",
    modules: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11],
    labs: [
      "lab-02-dataverse-modelo-datos",
      "lab-03-canvas-primera-app",
      "lab-04-model-driven-app",
      "lab-05-automate-aprobacion",
      "lab-61-capstone-maker-sistema-solicitudes",
    ],
    competencies: ["Canvas Apps", "Model-Driven Apps", "Dataverse básico", "Power Automate", "Power Fx"],
    status: "Disponible",
    capstoneLabSlug: "lab-61-capstone-maker-sistema-solicitudes",
    portfolioEvidence: [
      "Captura de la Canvas App funcionando (pantallas principales)",
      "Captura o log de una ejecución exitosa del flujo de aprobación",
      "Captura de acceso restringido probado con un segundo usuario",
      "Manual de usuario de 1-2 páginas",
    ],
    nextRouteSlug: "consultor-funcional",
  },
  {
    slug: "consultor-funcional",
    title: "Ruta Consultor Funcional",
    role: "Consultor que traduce necesidades de negocio en solución configurable",
    summary: "Conecta discovery, requerimientos, seguridad, procesos, UAT y documentación funcional con configuración real en Power Platform.",
    outcome: "Diseñar y entregar una solución funcional con requerimientos, backlog, seguridad, pruebas UAT y capacitación.",
    level: "Intermedio",
    accent: "#0078D4",
    modules: [1, 2, 4, 5, 9, 11, 15, 16, 17, 38, 39, 55],
    labs: [
      "lab-04-model-driven-app",
      "lab-09-dataverse-avanzado",
      "lab-55-uat-gonolive-y-auditoria-prompts",
      "lab-57-diseno-solucion-d365-sales-con-ia",
      "lab-62-capstone-consultor-funcional-proyecto-completo",
      "lab-101-jr-013-crm-functional-analyst-caso-integrado",
    ],
    competencies: ["Discovery", "Requerimientos", "Fit-Gap", "Seguridad funcional", "UAT", "Capacitación", "Backlog Azure DevOps"],
    status: "Parcial",
    gapNote: "Cubre bien Power Platform genérico (requerimientos, fit-gap, seguridad, UAT) y ahora también backlog funcional en Azure DevOps con historias de usuario y criterios de aceptación (LAB-101), pero todavía no tiene módulos dedicados de consultoría funcional específicos de Dynamics 365 CE por industria. Complementa esta ruta con Dynamics 365 Customer Engagement; usa F&O solo como referencia avanzada/archivada hasta que exista una especialización verificada.",
    capstoneLabSlug: "lab-62-capstone-consultor-funcional-proyecto-completo",
    portfolioEvidence: [
      "Acta de discovery con preguntas reales, no genéricas",
      "Backlog de historias de usuario con criterios de aceptación (LAB-101: Epics/Features/Historias en Azure DevOps)",
      "Matriz Fit-Gap y matriz de trazabilidad",
      "8 casos UAT con resultado",
      "Presentación funcional de 6-8 láminas",
    ],
    nextRouteSlug: "dynamics-365-customer-engagement",
  },
  {
    slug: "developer",
    title: "Ruta Developer",
    role: "Desarrollador Power Platform y consultor técnico",
    summary: "Profundiza en extensibilidad, integración, ALM, plugins, PCF, Web API, TypeScript, C# y revisión técnica asistida por IA.",
    outcome: "Extender Dataverse e integrar soluciones con código, APIs, componentes y pipelines controlados.",
    level: "Avanzado",
    accent: "#EA580C",
    modules: [13, 14, 18, 19, 21, 23, 24, 26, 27, 28, 50, 52, 53, 54],
    labs: [
      "lab-19-cicd-azure-devops",
      "lab-23-plugin-csharp",
      "lab-52-cli-conexion-tenant",
      "lab-53-exportar-revisar-solucion-con-ia",
      "lab-54-conectar-app-externa-dataverse",
      "lab-63-capstone-developer-solucion-tecnica-avanzada",
    ],
    competencies: ["Plugins C#", "PCF", "Dataverse Web API", "Custom Connectors", "ALM", "CI/CD"],
    status: "Disponible",
    capstoneLabSlug: "lab-63-capstone-developer-solucion-tecnica-avanzada",
    portfolioEvidence: [
      "Repositorio con el código del plugin/PCF/connector",
      "Resultado de la ejecución de los unit tests",
      "Solución exportada (.zip) o captura del pipeline ejecutado",
      "Documento técnico con decisiones no obvias",
    ],
    nextRouteSlug: "solution-architect",
  },
  {
    slug: "solution-architect",
    title: "Ruta Solution Architect",
    role: "Arquitecto de soluciones Microsoft Business Applications",
    summary: "Organiza estrategia de ambientes, gobernanza, seguridad, integración, datos, riesgos, costos y decisiones ejecutivas.",
    outcome: "Defender una arquitectura enterprise con ADRs, roadmap, modelo de gobierno, integración y plan operativo.",
    level: "Avanzado",
    accent: "#D13438",
    modules: [18, 19, 25, 30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41],
    labs: [
      "lab-19-cicd-azure-devops",
      "lab-32-coe-starter-kit",
      "lab-51-flujo-completo-humano-ia-ci",
      "lab-56-cambiar-entornos-dev-test-prod",
      "lab-60-proyecto-integrador-servicio-postventa",
    ],
    competencies: ["Gobernanza", "Seguridad", "ALM enterprise", "Integraciones", "Arquitectura de datos", "ADRs"],
    status: "Disponible",
    capstoneModuleId: 41,
    portfolioEvidence: [
      "Architecture Blueprint con ADRs y diagrama aprobado por mentor",
      "Solución desplegada en ambientes DEV/TEST",
      "Well-Architected Review con plan de remediación",
      "Presentación ejecutiva de 10 láminas",
    ],
    nextRouteSlug: "ai-copilot",
  },
  {
    slug: "dynamics-365-customer-engagement",
    title: "Ruta Dynamics 365 Customer Engagement",
    role: "Consultor funcional D365 CE para ventas y servicio",
    summary: "Profundiza en Sales, Customer Service, Customer Insights, Field Service y diseño funcional CE enterprise. Contact Center y F&O quedan como especializaciones opcionales, no como núcleo obligatorio.",
    outcome: "Diseñar procesos D365 CE end-to-end con pipeline, SLA, Customer 360, Field Service y frontera ERP clara sin asumir implementación F&O.",
    level: "Especialización",
    accent: "#4F6BED",
    modules: [1, 4, 9, 15, 20, 22, 30, 39, 53, 55, 56, 57, 58, 59, 61, 62, 64, 66],
    labs: [
      "lab-22-copilot-studio",
      "lab-55-uat-gonolive-y-auditoria-prompts",
      "lab-57-diseno-solucion-d365-sales-con-ia",
      "lab-58-customer-insights-segmento-journey",
      "lab-59-field-service-work-order-uat",
      "lab-60-proyecto-integrador-servicio-postventa",
      "lab-66-sales-lead-to-cash",
      "lab-67-customer-360-insights-data",
      "lab-68-customer-service-case-to-resolution",
      "lab-81-d365-sales-forecasting-pipeline-review",
      "lab-82-customer-service-sla-entitlements-routing",
      "lab-84-customer-insights-real-time-journey",
      "lab-85-customer-insights-data-unification",
      "lab-86-field-service-agreement-preventive-maintenance",
      "lab-87-field-service-mobile-offline-work-order",
      "lab-90-capstone-enterprise-d365",
    ],
    competencies: ["Sales Forecasting", "Customer Service SLA", "Customer Insights Data/Journeys", "Field Service", "Fit-Gap D365"],
    status: "Disponible",
    gapNote: "La ruta cubre Sales avanzado, Customer Service avanzado, Customer Insights - Data, Customer Insights - Journeys, Field Service end-to-end y capstone enterprise. Contact Center se mantiene como especialización opcional; F&O se conserva como archivo/futura especialización. La práctica real de forecasting, journeys, mobile offline y RSO requiere tenant/licencias correspondientes.",
    capstoneLabSlug: "lab-90-capstone-enterprise-d365",
    portfolioEvidence: [
      "Documento de diseño de 3-5 páginas (TO-BE, Fit-Gap)",
      "Matriz de trazabilidad y 8 casos UAT",
      "Diseño de Customer Insights Data/Journeys y de Field Service",
      "Matriz de configuración de colas, diseño de SLA con pausa/reanudación y dashboard de servicio (LAB-068/LAB-082)",
      "Matriz de forecast/pipeline y diseño de mobile offline",
      "Flujo de Power Automate con trigger, acciones y manejo de error",
      "Decisión de frontera ERP documentada sin asumir implementación F&O",
      "Capstone Enterprise D365 con Fit-Gap, ownership, roadmap, UAT y resumen ejecutivo",
    ],
    nextRouteSlug: "solution-architect",
  },
  {
    slug: "dynamics-365-customer-insights",
    title: "Ruta Dynamics 365 Customer Insights",
    role: "Consultor que diseña Customer 360, segmentación y journeys gobernados",
    summary: "Separa Customer Insights - Data y Customer Insights - Journeys para construir perfiles unificados, consentimiento, triggers y activación de audiencias sin mezclar CDP con ejecución de marketing.",
    outcome: "Diseñar un flujo Customer 360 + real-time journey con datos unificados, consentimiento, canal, métricas y límites claros de tenant/licencia.",
    level: "Especialización",
    accent: "#0D9488",
    modules: [20, 56, 57, 63, 65],
    labs: [
      "lab-58-customer-insights-segmento-journey",
      "lab-67-customer-360-insights-data",
      "lab-84-customer-insights-real-time-journey",
      "lab-85-customer-insights-data-unification",
      "lab-90-capstone-enterprise-d365",
    ],
    competencies: ["Customer Insights - Data", "Customer Insights - Journeys", "Consentimiento", "Segmentos", "Triggers", "Analytics"],
    status: "Disponible",
    gapNote: "La ejecución real requiere Customer Insights habilitado, canales/dominios configurados, datos de prueba y permisos. Sin tenant, la ruta se evalúa con diseño documentado, matriz de consentimiento y simulación de journey.",
    capstoneLabSlug: "lab-90-capstone-enterprise-d365",
    portfolioEvidence: [
      "Mapa de fuentes y reglas de unificación de Customer Insights - Data",
      "Segmentos y medidas con fórmula o criterio de negocio documentado",
      "Diseño de real-time journey con trigger, consentimiento, canal, salida y métricas",
      "Prueba negativa de consentimiento o exclusión de audiencia",
    ],
    nextRouteSlug: "dynamics-365-customer-engagement",
  },
  {
    slug: "dynamics-365-field-service",
    title: "Ruta Dynamics 365 Field Service",
    role: "Consultor CE especializado en operación de campo y ciclo de work orders",
    summary: "Profundiza en work orders, agreements, activos, inspecciones, inventario, mobile offline, scheduling y RSO desde una perspectiva end-to-end.",
    outcome: "Diseñar y validar un proceso Field Service completo con mantenimiento preventivo, ciclo de orden de trabajo, movilidad y criterios operativos.",
    level: "Especialización",
    accent: "#107C10",
    modules: [20, 56, 58, 65],
    labs: [
      "lab-59-field-service-work-order-uat",
      "lab-86-field-service-agreement-preventive-maintenance",
      "lab-87-field-service-mobile-offline-work-order",
      "lab-90-capstone-enterprise-d365",
    ],
    competencies: ["Work Orders", "Agreements", "Assets", "Inspections", "Mobile Offline", "Scheduling", "RSO"],
    status: "Disponible",
    gapNote: "La ejecución real requiere Dynamics 365 Field Service instalado, roles adecuados, recursos configurados y, para RSO/mobile offline, licenciamiento y configuración adicional. Sin tenant, se evalúa con matriz de diseño y simulación del ciclo.",
    capstoneLabSlug: "lab-90-capstone-enterprise-d365",
    portfolioEvidence: [
      "Diseño end-to-end de work order lifecycle",
      "Agreement de mantenimiento preventivo con recurrencia y evidencia esperada",
      "Matriz de mobile offline por perfil, tabla y conflicto",
      "Criterios de scheduling/RSO y restricciones operativas",
    ],
    nextRouteSlug: "dynamics-365-customer-engagement",
  },
  {
    slug: "finance-operations",
    title: "Archivo Finance & Operations",
    role: "Especialización futura para ERP, CRM e integración empresarial",
    summary: "Material conservado como archivo y futura especialización. No forma parte del progreso obligatorio ni de la promesa laboral base de PlanEstudio.",
    outcome: "Reconocer procesos ERP y fronteras CE + F&O a nivel conceptual; no declarar competencia F&O practitioner sin tenant, licencia, datos y mentoría de producto.",
    level: "Especialización",
    accent: "#8661C5",
    modules: [1, 18, 24, 31, 34, 35, 36, 38, 39, 41, 53, 59, 64, 65],
    labs: [
      "lab-19-cicd-azure-devops",
      "lab-54-conectar-app-externa-dataverse",
      "lab-56-cambiar-entornos-dev-test-prod",
      "lab-69-fo-process-mapping-erp-end-to-end",
      "lab-70-ce-fo-integration-architecture",
      "lab-64-capstone-fo-awareness-arquitectura-erp-crm",
      "lab-88-ce-fo-dual-write-ownership-matrix",
      "lab-89-fo-process-mapping-advanced",
      "lab-93-fo-finance-setup-walkthrough",
      "lab-94-fo-procure-to-pay-hands-on",
      "lab-95-fo-order-to-cash-hands-on",
      "lab-96-fo-inventory-products-setup",
      "lab-97-fo-project-operations-setup",
      "lab-98-fo-commerce-overview-hands-on",
      "lab-99-fo-security-duty-privilege-hands-on",
      "lab-100-fo-reporting-hands-on",
      "lab-90-capstone-enterprise-d365",
    ],
    competencies: ["ERP vs CRM", "Procesos ERP estándar", "Mapeo de procesos O2C/P2P/R2R/I2D", "Dual-write conceptual", "Virtual tables", "Data Management", "Gobernanza"],
    status: "Archivada / futura especialización",
    gapNote: "Contenido preservado para consulta avanzada. Los labs F&O hands-on LAB-093 a LAB-100 no están verificados contra tenant en vivo y no deben contar como ruta laboral disponible. Para reactivar esta ruta se requiere ambiente F&O real, datos maestros, licencias, validación paso a paso y revisión de un consultor F&O.",
    capstoneLabSlug: "lab-90-capstone-enterprise-d365",
    portfolioEvidence: [
      "5 mapas de proceso ERP (O2C/P2P/R2R/I2D/Project-to-Profit) con pasos, actores y sistema responsable (LAB-069)",
      "Diagrama Mermaid de integración y matriz de ownership de datos por entidad (LAB-070)",
      "Tabla de clasificación de procesos ERP vs. CRM con el proceso ERP estándar nombrado (O2C/P2P/R2R/I2D)",
      "Mapa de integración con dirección del dual-write",
      "Decisión justificada de dual-write vs. DMF vs. virtual tables para un caso concreto",
      "Setup financiero ejecutado en trial tenant: legal entity, calendario fiscal, catálogo de cuentas y dimensiones (LAB-093)",
      "Ciclo Procure-to-Pay y Order-to-Cash ejecutados end-to-end con manejo de discrepancia/parcialidad (LAB-094, LAB-095)",
      "Diseño de roles de seguridad F&O sin conflicto de segregación de funciones (LAB-099)",
      "Balance de comprobación y workspace con Power BI embebido documentados (LAB-100)",
      "Matriz de riesgos de la integración",
      "Documento ejecutivo de 1-2 páginas",
    ],
    nextRouteSlug: "solution-architect",
  },
  {
    slug: "rpa",
    title: "Ruta RPA Developer / Automation Engineer",
    role: "Profesional que diseña, construye, opera y diagnostica automatizaciones de escritorio",
    summary: "Especialización transversal en Power Automate Desktop, selección tecnológica, attended/unattended, selectores, Excel, web, legacy, ALM, soporte y gobierno.",
    outcome: "Automatizar un proceso administrativo end-to-end con PAD y Power Automate cloud, evidencia, pruebas, despliegue, runbook y RCA.",
    level: "Especialización",
    accent: "#6B4EFF",
    modules: [66, 67, 68, 69, 70, 71, 72, 73, 74, 75],
    labs: [
      "lab-104-rpa-primer-desktop-flow-mantenible",
      "lab-105-rpa-excel-consolidacion-ventas",
      "lab-106-rpa-automatizacion-web-portal",
      "lab-107-rpa-aplicacion-legacy-controlada",
      "lab-108-rpa-selectores-resiliencia",
      "lab-109-rpa-errores-idempotencia",
      "lab-110-rpa-cloud-desktop-end-to-end",
      "lab-111-rpa-despliegue-operacion-unattended",
      "lab-112-rpa-capstone-proceso-administrativo",
    ],
    competencies: ["PAD", "RPA attended/unattended", "Selectores", "Excel automation", "Web automation", "Legacy apps", "Idempotencia", "ALM", "Operación"],
    status: "Disponible",
    gapNote: "La ruta permite ejecución real o simulada según tenant/licencia. Unattended, machine groups y hosted machines requieren validar capacidades disponibles; sin licencia se entrega variante simulada claramente marcada.",
    capstoneLabSlug: "lab-112-rpa-capstone-proceso-administrativo",
    portfolioEvidence: [
      "Matriz de viabilidad RPA vs API/conector/cloud flow",
      "AS-IS, TO-BE y diagrama cloud + desktop",
      "Desktop flow con logs, manejo de errores e idempotencia",
      "Evidencia de pruebas positivas, negativas y reejecución sin duplicados",
      "Deployment checklist, rollback plan y runbook",
      "RCA de un incidente RPA y demo honesta de alcance simulado/tenant",
    ],
    nextRouteSlug: "developer",
  },
  {
    slug: "ai-copilot",
    title: "Ruta AI & Copilot",
    role: "Profesional que usa IA con control, seguridad y trazabilidad",
    summary: "Integra Copilot Studio, AI Builder, copilots de desarrollo, revisión de diffs, seguridad de prompts y flujos humano-IA-CI.",
    outcome: "Aplicar IA como acelerador responsable en desarrollo, consultoría, arquitectura y operación Power Platform/D365.",
    level: "Especialización",
    accent: "#9333EA",
    modules: [15, 22, 37, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 54, 55],
    labs: [
      "lab-22-copilot-studio",
      "lab-45-copilot-implementacion-guiada",
      "lab-51-flujo-completo-humano-ia-ci",
      "lab-55-uat-gonolive-y-auditoria-prompts",
      "lab-65-capstone-ai-copilot-agente-gobernado",
    ],
    competencies: ["Copilot Studio", "AI Builder", "Prompting técnico", "Revisión de diffs", "Seguridad IA", "Guardrails"],
    status: "Disponible",
    capstoneLabSlug: "lab-65-capstone-ai-copilot-agente-gobernado",
    portfolioEvidence: [
      "Documento de diseño del agente (alcance, temas, fuentes)",
      "Matriz de riesgos de IA y política de escalamiento humano",
      "Transcripts de 3 conversaciones de prueba",
      "Plan de monitoreo con métrica y frecuencia",
    ],
    nextRouteSlug: "developer",
  },
  {
    slug: "fundamentos-power-platform",
    title: "Ruta Fundamentos Power Platform",
    role: "Persona que nunca usó Power Platform ni Dataverse — punto de entrada absoluto",
    summary: "Exactamente el Nivel Básico (Módulos 1-8): Dataverse, Canvas Apps, Model-Driven Apps, Power Automate, Power BI y Power Fx desde cero, con tu primer proyecto integrado como cierre.",
    outcome: "Tener un ambiente Developer propio funcionando y haber construido tu primera app, flujo y tabla — sin asumir experiencia previa de ningún tipo.",
    level: "Inicial",
    accent: "#107C10",
    modules: [1, 2, 3, 4, 5, 6, 7, 8],
    labs: ["lab-02-dataverse-modelo-datos", "lab-03-canvas-primera-app", "lab-04-model-driven-app", "lab-05-automate-aprobacion"],
    competencies: ["Dataverse básico", "Canvas Apps", "Model-Driven Apps", "Power Automate básico", "Power BI básico", "Power Fx básico"],
    status: "Disponible",
    gapNote: "Corre completa en tu ambiente Microsoft 365 Developer personal (gratuito) — ver Ruta cero absoluta si todavía no lo tenés. No requiere ningún trial de Dynamics 365.",
    capstoneModuleId: 8,
    portfolioEvidence: [
      "Capturas del ambiente Developer activo",
      "Tabla personalizada con datos de prueba (Lab 02)",
      "Canvas App funcional conectada a Dataverse (Lab 03)",
      "Model-Driven App con formularios y vistas (Lab 04)",
      "Flujo de aprobación en Power Automate (Lab 05)",
    ],
    nextRouteSlug: "maker",
  },
  {
    slug: "dynamics-365-sales",
    title: "Ruta Dynamics 365 Sales",
    role: "Persona que quiere especializarse en el proceso comercial de Dynamics 365 CE",
    summary: "Cuentas, contactos, leads, oportunidades, forecasting, pipeline review y sales operations — separado de Customer Service y Customer Insights para practicar cada producto sin mezclar trials.",
    outcome: "Diseñar y operar un proceso lead-to-opportunity completo, con matriz de forecast y política de pipeline hygiene defendibles en una entrevista de Consultor Funcional.",
    level: "Especialización",
    accent: "#0D9488",
    modules: [1, 9, 61],
    labs: ["lab-57-diseno-solucion-d365-sales-con-ia", "lab-66-sales-lead-to-cash", "lab-81-d365-sales-forecasting-pipeline-review", "lab-102-jr-014-sales-lead-to-cash-job-test"],
    competencies: ["Cuentas y contactos", "Leads y calificación", "Oportunidades y pipeline", "Forecasting", "Productos y listas de precios", "Sales operations"],
    status: "Disponible",
    gapNote: "Requiere activar el trial de Dynamics 365 Sales específico (un ambiente Dataverse-only no lo trae instalado) — ver Matriz de entornos y trials. Sin trial, el diseño del proceso es practicable, pero validar visualmente el forecast requiere tenant.",
    capstoneLabSlug: "lab-102-jr-014-sales-lead-to-cash-job-test",
    portfolioEvidence: [
      "Diagrama lead-to-opportunity con criterios de calificación",
      "Matriz de forecast completada con datos de prueba",
      "Política de pipeline hygiene documentada",
      "Resultado del job test JR-014 (Lab 102)",
    ],
    nextRouteSlug: "dynamics-365-customer-service",
  },
  {
    slug: "dynamics-365-customer-service",
    title: "Ruta Dynamics 365 Customer Service",
    role: "Persona que quiere especializarse en atención y servicio al cliente de Dynamics 365 CE",
    summary: "Casos, colas, SLA, entitlements, knowledge base y routing — separado de Sales y Customer Insights para practicar cada producto sin mezclar trials.",
    outcome: "Diseñar y operar un proceso de servicio completo, con matriz de SLA y árbol de decisión de agente defendibles en una entrevista de Consultor Funcional.",
    level: "Especialización",
    accent: "#0D9488",
    modules: [1, 9, 62],
    labs: ["lab-68-customer-service-case-to-resolution", "lab-82-customer-service-sla-entitlements-routing", "lab-77-jr-007-customer-service-specialist-simulation", "lab-103-jr-015-functional-post-go-live-incident-simulation"],
    competencies: ["Casos", "Colas", "SLA y entitlements", "Knowledge base", "Routing", "Métricas de servicio"],
    status: "Disponible",
    gapNote: "Requiere activar el trial de Dynamics 365 Customer Service específico (trial separado del de Sales) — ver Matriz de entornos y trials. Diseñar tipos de caso y matrices de SLA es practicable sin tenant; validar calendario, pausas y routing ejecutándose requiere ambiente real.",
    capstoneLabSlug: "lab-77-jr-007-customer-service-specialist-simulation",
    portfolioEvidence: [
      "Matriz de SLA con calendario, pausas y escalamiento",
      "Árbol de decisión de agente",
      "Diseño de colas y routing por producto/severidad",
      "Resultado de la simulación JR-007 (Lab 77)",
    ],
    nextRouteSlug: "dynamics-365-customer-insights-data",
  },
  {
    slug: "dynamics-365-customer-insights-data",
    title: "Ruta Dynamics 365 Customer Insights - Data",
    role: "Persona que quiere especializarse en unificación de datos de cliente (CDP)",
    summary: "Fuentes de datos, calidad, ingesta, unificación, coincidencia, perfiles, medidas y segmentos — separado explícitamente de Customer Insights - Journeys, que es ejecución de marketing, no CDP.",
    outcome: "Diseñar y ejecutar una unificación de perfiles de cliente con al menos una fuente de datos real y un segmento resultante.",
    level: "Especialización",
    accent: "#0D9488",
    modules: [1, 9, 58],
    labs: ["lab-67-customer-360-insights-data", "lab-85-customer-insights-data-unification"],
    competencies: ["Fuentes de datos", "Calidad de datos", "Unificación de perfiles", "Coincidencia (matching)", "Medidas", "Segmentos"],
    status: "Disponible",
    gapNote: "Requiere activar Customer Insights en el trial correspondiente — ver Matriz de entornos y trials. Sin trial, el diseño de fuentes/unificación es practicable, pero validar perfiles unificados reales requiere ambiente activo.",
    capstoneLabSlug: "lab-85-customer-insights-data-unification",
    portfolioEvidence: [
      "Diagrama de fuentes de datos y reglas de unificación",
      "Matriz de calidad de datos (duplicados, campos obligatorios)",
      "Segmento resultante con criterio documentado",
    ],
    nextRouteSlug: "dynamics-365-customer-insights-journeys",
  },
  {
    slug: "dynamics-365-customer-insights-journeys",
    title: "Ruta Dynamics 365 Customer Insights - Journeys",
    role: "Persona que quiere especializarse en ejecución de journeys de marketing",
    summary: "Consentimiento, segmentos, formularios, emails, triggers y journeys en tiempo real — separado explícitamente de Customer Insights - Data (CDP).",
    outcome: "Diseñar y publicar un journey con consentimiento, trigger y al menos un canal de comunicación configurado.",
    level: "Especialización",
    accent: "#0D9488",
    modules: [1, 9, 64],
    labs: ["lab-58-customer-insights-segmento-journey", "lab-84-customer-insights-real-time-journey"],
    competencies: ["Consentimiento y cumplimiento", "Segmentos", "Formularios", "Emails", "Triggers", "Journeys en tiempo real"],
    status: "Disponible",
    gapNote: "Requiere activar Customer Insights - Journeys en el trial correspondiente — ver Matriz de entornos y trials. Sin trial, el diseño del journey es practicable, pero validar envío/consentimiento real requiere ambiente activo.",
    capstoneLabSlug: "lab-84-customer-insights-real-time-journey",
    portfolioEvidence: [
      "Diagrama de journey con puntos de consentimiento",
      "Segmento de entrada al journey",
      "Captura del journey publicado (si hay ambiente activo) o diseño documentado",
    ],
    nextRouteSlug: "empleabilidad",
  },
  {
    slug: "empleabilidad",
    title: "Ruta Empleabilidad y Proyectos Integradores",
    role: "Cualquier persona que ya avanzó en al menos una especialización y quiere armar evidencia de portafolio defendible",
    summary: "Reúne los proyectos integradores de cada nivel y los job tests (JR-001 a JR-015) en una sola ruta transversal — no reemplaza a ninguna especialización, la complementa con evidencia y práctica de entrevista.",
    outcome: "Tener un portafolio con evidencia concreta por ruta, checklist de habilidades laborales completado, y al menos un job test resuelto con retroalimentación honesta.",
    level: "Especialización",
    accent: "#EA580C",
    modules: [8, 17, 30],
    labs: [
      "lab-71-jr-001-model-driven-app-job-test",
      "lab-72-jr-002-crm-javascript-customization",
      "lab-77-jr-007-customer-service-specialist-simulation",
      "lab-79-jr-009-technical-interview-simulation",
      "lab-101-jr-013-crm-functional-analyst-caso-integrado",
      "lab-102-jr-014-sales-lead-to-cash-job-test",
      "lab-103-jr-015-functional-post-go-live-incident-simulation",
    ],
    competencies: ["Portafolio de evidencia", "CV/LinkedIn práctico", "Entrevista técnica", "Casos prácticos tipo empresa", "Checklist de habilidades laborales"],
    status: "Disponible",
    gapNote: "Prepara criterio, vocabulario y evidencia de portafolio defendible en entrevista — no sustituye experiencia laboral verificable ni garantiza empleo. Fluidez de inglés o feedback de reclutadores reales queda fuera de alcance de autoestudio.",
    capstoneLabSlug: "lab-79-jr-009-technical-interview-simulation",
    portfolioEvidence: [
      "Al menos 3 job tests (JR-0xx) completados con evidencia guardada",
      "CV y perfil de LinkedIn ajustados con el vocabulario de tu ruta principal",
      "Resultado de la simulación de entrevista técnica (Lab 79)",
      "Checklist de habilidades laborales de tu ruta principal completado",
    ],
  },
];

export function getAllProfessionalRoutes(): ProfessionalRoute[] {
  return PROFESSIONAL_ROUTES;
}

export function getProfessionalRouteBySlug(slug: string): ProfessionalRoute | undefined {
  return PROFESSIONAL_ROUTES.find((route) => route.slug === slug);
}
